services:
  - type: web
    name: csonic-bot-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    region: frankfurt
    runtime: node
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: DB_PATH
        value: ./database/businesses.db

